apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.payment.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db1
  namespace: {{ .Values.payment.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db1
  template:
    metadata:
      labels:
        app: db1
    spec:
      containers:
        - name: db1
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: mydb
