apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: {{ .Values.payment.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: {{ .Values.payment.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@db1:5432/mydb
